### ISSUE TITLE
panic: interface conversion: interface {} is string, not map[string]

### ISSUE THREAD

**Issue by RodneyRichardson** [opensbom-generator/spdx-sbom-generator#252]
## Summary

The builds for all merge requests are failing with the same error. 

This looks to have been introduced into the main branch with #250 (which was merged, despite the build failing!), or maybe that's just the first merge that was performed after there was a change to some underlying package).

```
--- FAIL: TestNPM (0.02s)
    --- FAIL: TestNPM/test_list_all_modules (0.00s)
panic: interface conversion: interface {} is string, not map[string]interface {} [recovered]
	panic: interface conversion: interface {} is string, not map[string]interface {}
goroutine 40 [running]:
testing.tRunner.func1.2({0x876300, 0xc003247f20})
	/opt/hostedtoolcache/go/1.18.3/x64/src/testing/testing.go:[138](https://github.com/RodneyRichardson/spdx-sbom-generator/runs/7316980646?check_suite_focus=true#step:7:139)9 +0x24e
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.18.3/x64/src/testing/testing.go:1392 +0x39f
panic({0x876300, 0xc003247f20})
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/panic.go:838 +0x207
github.com/spdx/spdx-sbom-generator/pkg/modules/npm.appendDependencies(...)
	/home/runner/work/spdx-sbom-generator/spdx-sbom-generator/pkg/modules/npm/handler.go:372
github.com/spdx/spdx-sbom-generator/pkg/modules/npm.appendNestedDependencies(0x8e5420?)
	/home/runner/work/spdx-sbom-generator/spdx-sbom-generator/pkg/modules/npm/handler.go:359 +0x48a
github.com/spdx/spdx-sbom-generator/pkg/modules/npm.(*npm).buildDependencies(0xc00316dde8, {0xc000154c30, 0x4e}, 0x8?)
	/home/runner/work/spdx-sbom-generator/spdx-sbom-generator/pkg/modules/npm/handler.go:209 +0x439
github.com/spdx/spdx-sbom-generator/pkg/modules/npm.(*npm).ListModulesWithDeps(0x8f7a08?, {0xc000154c30, 0x4e}, {0x1?, 0x1?})
	/home/runner/work/spdx-sbom-generator/spdx-sbom-generator/pkg/modules/npm/handler.go:185 +0x1ae
github.com/spdx/spdx-sbom-generator/pkg/modules/npm.TestListAllModules(0x0?)
	/home/runner/work/spdx-sbom-generator/spdx-sbom-generator/pkg/modules/npm/handler_test.go:104 +0x1aa
testing.tRunner(0xc0030fbd40, 0x939038)
	/opt/hostedtoolcache/go/1.18.3/x64/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.18.3/x64/src/testing/testing.go:1486 +0x35f
FAIL	github.com/spdx/spdx-sbom-generator/pkg/modules/npm	0.232s
```

## Expected behavior

All tests should pass.

## Repository

Which repository causes this error?

- https://github.com/spdx/spdx-sbom-generator

## Acceptance Criteria

1. All existing unit tests pass

## References

- https://github.com/opensbom-generator/spdx-sbom-generator/pull/250/checks

**Comment by preston** [comment]
v0.0.15 as installed via `brew install spdx-sbom-generator` (on macOS) throws the error for npm-based projects. I've tried on several projects and it consistently blows up this way. :-(

**Comment by richardtallent-erm** [comment]
I'm having the same issue with the pre-compiled Windows 64-bit binary on npm projects:

```shell
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
spdx-sbom-generator/internal/modules/npm.getPackageDependencies(0xc002f381b0, 0xd43bbb, 0xc, 0x1)
        /github/workspace/internal/modules/npm/handler.go:295 +0x6c7
spdx-sbom-generator/internal/modules/npm.(*npm).buildDependencies(0xc00009e0a0, 0xd3abf5, 0x1, 0xc002f381b0, 0xc0000ac0c8, 0xb80f9a, 0xc002f3e140, 0x11, 0x1)
        /github/workspace/internal/modules/npm/handler.go:185 +0x308
spdx-sbom-generator/internal/modules/npm.(*npm).ListModulesWithDeps(0xc00009e0a0, 0xd3abf5, 0x1, 0x0, 0x0, 0x1, 0x1, 0xd2ea00)
        /github/workspace/internal/modules/npm/handler.go:170 +0x208
spdx-sbom-generator/internal/modules.(*Manager).Run(0xc002ea72c0, 0x4, 0xd66122)
        /github/workspace/internal/modules/modules.go:94 +0x154
spdx-sbom-generator/internal/handler.(*spdxHandler).Run(0xc002ece0c0, 0x7, 0xd3abf5)
        /github/workspace/internal/handler/spdx.go:73 +0x2f5
main.generate(0x16558a0, 0x167d128, 0x0, 0x0)
        /github/workspace/cmd/generator/generator.go:105 +0x43a
github.com/spf13/cobra.(*Command).execute(0x16558a0, 0xc00004e1a0, 0x0, 0x0, 0x16558a0, 0xc00004e1a0)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x16558a0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        /github/workspace/cmd/generator/generator.go:37 +0x64
```

**Comment by nishakm** [comment]
> I'm having the same issue with the pre-compiled Windows 64-bit binary on npm projects:
> 
> ```shell
> panic: interface conversion: interface {} is nil, not string
> 
> goroutine 1 [running]:
> spdx-sbom-generator/internal/modules/npm.getPackageDependencies(0xc002f381b0, 0xd43bbb, 0xc, 0x1)
>         /github/workspace/internal/modules/npm/handler.go:295 +0x6c7
> spdx-sbom-generator/internal/modules/npm.(*npm).buildDependencies(0xc00009e0a0, 0xd3abf5, 0x1, 0xc002f381b0, 0xc0000ac0c8, 0xb80f9a, 0xc002f3e140, 0x11, 0x1)
>         /github/workspace/internal/modules/npm/handler.go:185 +0x308
> spdx-sbom-generator/internal/modules/npm.(*npm).ListModulesWithDeps(0xc00009e0a0, 0xd3abf5, 0x1, 0x0, 0x0, 0x1, 0x1, 0xd2ea00)
>         /github/workspace/internal/modules/npm/handler.go:170 +0x208
> spdx-sbom-generator/internal/modules.(*Manager).Run(0xc002ea72c0, 0x4, 0xd66122)
>         /github/workspace/internal/modules/modules.go:94 +0x154
> spdx-sbom-generator/internal/handler.(*spdxHandler).Run(0xc002ece0c0, 0x7, 0xd3abf5)
>         /github/workspace/internal/handler/spdx.go:73 +0x2f5
> main.generate(0x16558a0, 0x167d128, 0x0, 0x0)
>         /github/workspace/cmd/generator/generator.go:105 +0x43a
> github.com/spf13/cobra.(*Command).execute(0x16558a0, 0xc00004e1a0, 0x0, 0x0, 0x16558a0, 0xc00004e1a0)
>         /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2b1
> github.com/spf13/cobra.(*Command).ExecuteC(0x16558a0, 0x0, 0x0, 0x0)
>         /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x350
> github.com/spf13/cobra.(*Command).Execute(...)
>         /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
> main.main()
>         /github/workspace/cmd/generator/generator.go:37 +0x64
> ```

@richardtallent-erm Would you be able to provide a package-lock.json file for any of your npm projects? It looks like the parser is broken.

**Comment by richardtallent-erm** [comment]
Everything I'm working on currently is proprietary, so I don't have a "clean" reproducible file. That said, there are two "special" `package.json` dependencies that could possibly trip up a parser:

```js
// A reference to a local git submodule folder, e.g.:
"submodule-name": "file:submodule-name",

// A reference to a file in a public GitHub repo that isn't packaged on npm:
"filename.json": "github:repo-name/filename.json",
```

I also have a FontAwesome commercial license, so the repository for those packages is a private one, not npm.
