### ISSUE TITLE
SPDX parser and verifier

### ISSUE THREAD

**Issue by rjb4standards** [opensbom-generator/spdx-sbom-generator#261]
## Summary

Requesting an SPDX V 2.3 parser and validator function with this release that processes multiple SPDX SBOM files in a directory

## Background

Hoping an SPDX V 2.3 validator will be included in the released product.

## User Story

- I want to validate SPDX V 2.3 SBOM's en mass in an automated fashion, which the online tool does not support

## Acceptance Criteria

All SPDX V 2.3 SBOM's in a file directory are parsed and a single results file is produced containing all results for each validated SBOM

**Comment by nishakm** [comment]
I think parsing and validation is done with the [SPDX golang tools](https://github.com/spdx/tools-golang). @lumjjb

**Comment by lumjjb** [comment]
yes! we do have a parser - and we have plans to do spdx 2.3 in the roadmap!
